### ISSUE TITLE
提个建议，关于代码排版

### ISSUE THREAD

**Issue by liujiajie32** [tjwhm/cpp-#1]
关于代码缩进，建议统一使用空格取代Tab，这样能在不同的文本编译器和HTML页面上实现一致的显示效果。依照个人习惯，常用2个或4个空格代替一个Tab。

祝编码愉快  : )

**Comment by tjwhm** [comment]
谢谢家杰哥~

**Comment by tjwhm** [comment]
谢谢家杰哥，我这就去修改 IDE 一键格式化的设置~
